### ISSUE TITLE
Dynamic Graph support for PCSR approach

### ISSUE THREAD

**Issue by JoelMathewC** [bfGraph/Seastar#18]
We will need to work out this math on a smaller dataset and a custom kernel outside Seastar. The challenge is really in dealing with the spaces in the PMA format. We'll track the progress on this topic in this thread.

**Comment by nithinmanoj10** [comment]
# Edge ID Problem

Since PCSR will give us the edges in a sorted manner, we can pre-process any dataset we are using such that the edges and corresponding edge-weights are also sorted in that order.

**Comment by nithinmanoj10** [comment]
## Update

🥳🥳It works. Had to make a change in template to include `if(src_id == -1 || dst_id == -1)`. Additionally `row_offsets`, `col_indices` and `eids` were moved to GPU from `SeastarGraph` class itself. The base graph cache was temporarily disabled since it does not handle the new tensor format for attributes.

Checklist for wrapping this up

- [ ] Cleanup template
- [ ] Decide on the appropriate location to move  `row_offsets`, `col_indices` and `eids` to GPU
- [ ] Fix base_graph_cache
- [ ] Find a better logic for reverse_graph_init and make sure corresponding edge_ids are handled
- [ ] Fix hacky update graph methods
- [ ] maybe move reverse graph init into update_graph_backward function
- [ ] Benchmark against a large dataset

**Comment by JoelMathewC** [comment]
Decided to reverse the graph at the start of backpropagation. The possible alternatives we explored was

1. Storing a forward and a reverse edge with value 1/-1 to identify them when processing them in kernel: The problem with this approach was that it will make the column indices of size 2N.
2. Trying to reverse the CSR: This will take O(n*N*logn), n is the number of nodes, N is the size of the column indices vector

Additionally the benefit of this approach is that this has to be done only at the start of backward prop of the first epoch, it is cached for every upcoming backwardprop in every epoch.

**Comment by nithinmanoj10** [comment]
# Possible fix of PCSR

Currently PCSR implementation is having a node list, which contains beginning, dest, num_neighbours information. row_offset is built from node list in O(N). Need to find a suitable and efficient fix so that it building the CSR arrays are done in O(1).

Similarly for finding column_indices as well

**Comment by JoelMathewC** [comment]
## Exploring the eids issue

We need a list of edge ids to be provided to the kernel during backward and forward propagation. After much deliberation we have realized that we cannot include the edge ids in the preprocessed data since the edge id of an edge would have to change with time. Hence it has to be handled when the CSR arrays are obtained from PCSR.

We know that during forward prop, for each timestamp we can label every edge from 1 to N, in that order. However due to the structure difference between the CSR of a graph and the CSR of the reverse of that graph, this ordering cannout be obtained during the corresponding backward propagation.

The solution that we can finalize on is, during a backward propagation we would need access to the original graph at that timestamp and its reverse (the one used for forward prop). We would do a binary search on the reverse graph csr to obtain the eid for each edge in the original graph. We can perform the complexity analysis of this approach to see if there is still a benefit to using PCSR. We are performing the comparison with a naive approach of maintaining CSR arrays and inserting to them directly

```
Let 
    N -> be number of nodes
    E -> number of edges to be added (E = 0.1e)
    e -> number of edges in the graph initially
    D -> average number of neighbours of a node

PCSR approach
----------------
Adding an edge to PCSR -> O((logN)^2) time
To add E edges -> O( E * (logN)^2 ) = O( 0.1 * e * (logN)^2 ) = O( e * (logN)^2 )
To build the eids for the updated graph -> (e+E) * log(D) = e * log(D)

Since D < N
log(D) < (logN)^2)
Complexity: O( e * (logN)^2 )


Inserting to CSR approach
--------------------------
Adding an edge to CSR -> O(e) time
To add E edges -> O( E * e ) = O(e^2)
To build the eids for the updated graph -> (e+E) * log(D)

Since D < N < e
Complexity: O( e^2 )
```

Hence there is still a benefit to the approach. And actually there isn't a need to optimize eids because that is not the most time consuming task.

Note: The original graph is used for backward prop and the reverse is used for forward prop. This is because of the way the kernel is designed.

**Comment by nithinmanoj10** [comment]
## Pending

- [ ] Abstraction SeastarGraph, SeastarDynamicGraph (inheriting from SeastarGraph)
- [ ] Dataset loader
- [ ] Ensure that only necessary methods and attributes are exposed in SeastarGra[h
- [ ] Benchmark on large dataset
- [ ] Remove forward cacheing in SeastarGraph
- [ ] Handle seastar making a call to update_graph_forward (add check to see if it is a dynamic graph then do)

**Comment by JoelMathewC** [comment]
All of th issues have been resolved and PCSR support has been officially added to Seastar
